name: example-environment
channels:
  - conda-forge
dependencies:
  - cython
  - scipy
  - numpy
  - qutip
  - matplotlib
  - h5py
  - tqdm
  - cycler
  - pathos
  - dill
  - scqubits==1.3.2
  - ipywidgets
